spring:
  config:
    import:
      - cryptocompare.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_currencies_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true

coingecko:
  api:
    key: 
    rate-limit: 30
    refresh-rate: 60000
